#!/bin/sh /etc/rc.common

START=96
STOP=10
USE_PROCD=1

start_service() {
	/usr/sbin/xg040g-cpuctl apply-config
	procd_open_instance
	procd_set_param command /usr/sbin/xg040g-cpu-monitor
	procd_set_param respawn 3600 5 5
	procd_close_instance
}

stop_service() {
	/usr/sbin/xg040g-cpuctl set 1200 >/dev/null 2>&1 || true
}

service_triggers() {
	procd_add_reload_trigger xg040g-performance
}
